"ui.background" = "light-black"
"ui.text" = "white"
"ui.menu" = { fg = "black", bg = "light-gray" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.popup" = { modifiers = ["reversed"] }
"ui.linenr" = "gray"
"ui.linenr.selected" = { fg = "white", bg = "black", modifiers = ["bold"] }
"ui.selection" = { fg = "black", bg = "blue" }
"ui.selection.primary" = { fg = "white", bg = "blue" }
"comment" = { fg = "gray" }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"variable" = "red"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "yellow"
"type" = "yellow"
"ui.cursor.match" = { fg = "yellow", modifiers = ["underlined"] }
"string"  = "green"
"variable.other.member" = "green"
"constant.character.escape" = "cyan"
"function" = "blue"
"constructor" = "blue"
"special" = "blue"
"keyword" = "magenta"
"label" = "magenta"
"namespace" = "magenta"
"ui.help" = { fg = "white", bg = "black" }

"ui.virtual.indent-guide" = "black"
"ui.virtual.indent-guide.selected" = { bg = "black"}

"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "black" }
"info" = "blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "red"


[palette]
black     = "#414868"
blue      = "#7aa2f7"
cyan      = "#7dcfff"
green     = "#9ece6a"
magenta   = "#bb9af7"
red       = "#f7768e"
white     = "#c0caf5"
yellow    = "#e0af68"
gray      = "#565f89"

light-black   = "#32344a"
light-blue    = "#7aa2f7"
light-cyan    = "#7dcfff"
light-green   = "#9ece6a"
light-magenta = "#bb9af7"
light-red     = "#f7768e"
light-white   = "#c0caf5"
light-yellow  = "#e0af68"
light-gray    = "#9aa5ce"

background = "#1a1b26"
foreground = "#a9b1d6"
